In [1]:
import pandas as pd
from os.path import join

In [2]:
azrael = pd.read_csv("data/bnr_azrael_20240611_detailed.csv.gz")
jhove = pd.read_csv("data/jhove_synth.csv.gz")

/tmp/ipykernel_5179/2774709951.py:1: DtypeWarning: Columns (9,10,18) have mixed types. Specify dtype option on import or set low_memory=False.
  azrael = pd.read_csv("data/bnr_azrael_20240611_detailed.csv.gz")

In [3]:
azrael.columns

Index(['name', 'path', 'size', 'last_content_modification_date',
       'last_metadata_modification_date', 'bnr_file_id', 'path0', 'path1',
       'path2', 'path3', 'path4', 'last_content_modification_date_',
       'last_metadata_modification_date_', 'size_mo', 'extension', 'mimetype',
       'guessed_extension', 'file_type', 'jhove_chunk_id'],
      dtype='object')

In [4]:
azrael['uri'] = azrael['path'] + "/" + azrael['name']

In [6]:
jhove.columns

Index(['jhove_uri', 'jhove_lastModified', 'jhove_format', 'jhove_version',
       'jhove_mimeType', 'jhove_size', 'jhove_imageWidth', 'jhove_imageHeight',
       'jhove_samplingFrequencyUnit', 'jhove_x_resolution',
       'jhove_y_resolution', 'jhove_chunk_id'],
      dtype='object')

In [6]:
azrael = azrael.merge(jhove, left_on = 'uri', right_on = 'jhove_uri', how='left')

In [7]:
azrael

,name,path,size,last_content_modification_date,last_metadata_modification_date,bnr_file_id,path0,path1,path2,path3,...,jhove_format,jhove_version,jhove_mimeType,jhove_size,jhove_imageWidth,jhove_imageHeight,jhove_samplingFrequencyUnit,jhove_x_resolution,jhove_y_resolution,jhove_chunk_id_y
0,RBX_AMR_AFF_001_D_0001_1.tif,BNR_SAUV/AMR/AMR_AFF,143190155,1.537953e+09,1.346326e+09,bnr_00000001,BNR_SAUV,AMR,AMR_AFF,NaN,...,TIFF,5.0,image/tiff,143190155.0,7840.0,6088.0,in.,300.0,300.0,20240611_00000001
1,RBX_AMR_AFF_001_D_0002_1.tif,BNR_SAUV/AMR/AMR_AFF,73202507,1.537953e+09,1.346326e+09,bnr_00000002,BNR_SAUV,AMR,AMR_AFF,NaN,...,TIFF,5.0,image/tiff,73202507.0,4008.0,6088.0,in.,300.0,300.0,20240611_00000001
2,RBX_AMR_AFF_001_D_0003_1.tif,BNR_SAUV/AMR/AMR_AFF,175634315,1.537953e+09,1.346326e+09,bnr_00000003,BNR_SAUV,AMR,AMR_AFF,NaN,...,TIFF,5.0,image/tiff,175634315.0,6776.0,8640.0,in.,300.0,300.0,20240611_00000001
3,RBX_AMR_AFF_001_D_0004_1.tif,BNR_SAUV/AMR/AMR_AFF,133094411,1.537953e+09,1.346326e+09,bnr_00000004,BNR_SAUV,AMR,AMR_AFF,NaN,...,TIFF,5.0,image/tiff,133094411.0,6224.0,7128.0,in.,300.0,300.0,20240611_00000001
4,RBX_AMR_AFF_001_D_0005_1.tif,BNR_SAUV/AMR/AMR_AFF,142771211,1.537953e+09,1.346326e+09,bnr_00000005,BNR_SAUV,AMR,AMR_AFF,NaN,...,TIFF,5.0,image/tiff,142771211.0,6064.0,7848.0,in.,300.0,300.0,20240611_00000001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2316726,4_actualisation_infos_sauvegarde_BnR_160916.doc,Procedures/Point 2016,29184,1.623768e+09,1.595599e+09,bnr_02316727,Procedures,Point 2016,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2316727,Thumbs.db,Procedures/Point 2016,24576,1.696635e+09,1.696589e+09,bnr_02316728,Procedures,Point 2016,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2316728,droidacces_BNR_160923.ods,Procedures/Point 2016,12855,1.614956e+09,1.595599e+09,bnr_02316729,Procedures,Point 2016,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2316729,mess_20160927.docx,Procedures/Point 2016,13745,1.694695e+09,1.595600e+09,bnr_02316730,Procedures,Point 2016,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2316730,mess_20170704.docx,Procedures/Point 2017,15381,1.614956e+09,1.595600e+09,bnr_02316731,Procedures,Point 2017,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
azrael = azrael[~azrael['jhove_uri'].isna()]

In [14]:
azrael[azrael['mimetype'] != azrael['jhove_mimeType']]

,name,path,size,last_content_modification_date,last_metadata_modification_date,bnr_file_id,path0,path1,path2,path3,...,jhove_format,jhove_version,jhove_mimeType,jhove_size,jhove_imageWidth,jhove_imageHeight,jhove_samplingFrequencyUnit,jhove_x_resolution,jhove_y_resolution,jhove_chunk_id_y
108488,RBX_MED_CP_A05_L5_S2_001.tif,BNR_SAUV/MED/MED_CP,10448838,1.537965e+09,1.234879e+09,bnr_00108489,BNR_SAUV,MED,MED_CP,NaN,...,bytestream,NaN,application/octet-stream,10448838.0,NaN,NaN,NaN,NaN,NaN,20240611_00000217
115644,RBX_MED_MON_8_116690_002.tif,BNR_SAUV/MED/MED_MON,33884149,1.537966e+09,1.320942e+09,bnr_00115645,BNR_SAUV,MED,MED_MON,NaN,...,bytestream,NaN,application/octet-stream,33884149.0,NaN,NaN,NaN,NaN,NaN,20240611_00000232
120893,RBX_MED_MS_202_037.tif,BNR_SAUV/MED/MED_MS,182100577,1.537969e+09,1.320853e+09,bnr_00120894,BNR_SAUV,MED,MED_MS,NaN,...,bytestream,NaN,application/octet-stream,182100577.0,NaN,NaN,NaN,NaN,NaN,20240611_00000242
123412,RBX_MED_MS_306_028.tif,BNR_SAUV/MED/MED_MS,50116050,1.537970e+09,1.333700e+09,bnr_00123413,BNR_SAUV,MED,MED_MS,NaN,...,bytestream,NaN,application/octet-stream,50116050.0,NaN,NaN,NaN,NaN,NaN,20240611_00000247
123419,RBX_MED_MS_306_034.tif,BNR_SAUV/MED/MED_MS,51242118,1.537970e+09,1.333701e+09,bnr_00123420,BNR_SAUV,MED,MED_MS,NaN,...,bytestream,NaN,application/octet-stream,51242118.0,NaN,NaN,NaN,NaN,NaN,20240611_00000247
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185051,PRA_CRT_19080905_006.tif,BNR_SAUV/MED/MED_PRA/PRA_CRT,32765903,1.699183e+09,1.288864e+09,bnr_00185052,BNR_SAUV,MED,MED_PRA,PRA_CRT,...,bytestream,NaN,application/octet-stream,32765903.0,NaN,NaN,NaN,NaN,NaN,20240611_00000370
185052,PRA_CRT_19080906_001.tif,BNR_SAUV/MED/MED_PRA/PRA_CRT,33835332,1.699183e+09,1.288864e+09,bnr_00185053,BNR_SAUV,MED,MED_PRA,PRA_CRT,...,bytestream,NaN,application/octet-stream,33835332.0,NaN,NaN,NaN,NaN,NaN,20240611_00000370
185053,PRA_CRT_19080906_002.tif,BNR_SAUV/MED/MED_PRA/PRA_CRT,34677078,1.699183e+09,1.288864e+09,bnr_00185054,BNR_SAUV,MED,MED_PRA,PRA_CRT,...,bytestream,NaN,application/octet-stream,34677078.0,NaN,NaN,NaN,NaN,NaN,20240611_00000370
185054,PRA_CRT_19080906_003.tif,BNR_SAUV/MED/MED_PRA/PRA_CRT,32633115,1.699183e+09,1.288864e+09,bnr_00185055,BNR_SAUV,MED,MED_PRA,PRA_CRT,...,bytestream,NaN,application/octet-stream,32633115.0,NaN,NaN,NaN,NaN,NaN,20240611_00000370
185055,PRA_CRT_19080906_004.tif,BNR_SAUV/MED/MED_PRA/PRA_CRT,34703665,1.699183e+09,1.288864e+09,bnr_00185056,BNR_SAUV,MED,MED_PRA,PRA_CRT,...,bytestream,NaN,application/octet-stream,34703665.0,NaN,NaN,NaN,NaN,NaN,20240611_00000370

In [2]:
import pandas as pd
import os

all_results = []
files = [f for f in os.listdir('data/jhove_csv')]
for filename in sorted(files):
    print(filename)
    tmp = pd.read_csv(f"data/jhove_csv/{filename}", usecols=['jhove_uri', 'jhove_lastModified', 'jhove_format', 'jhove_version',
       'jhove_mimeType', 'jhove_size', 'jhove_imageWidth', 'jhove_imageHeight',
       'jhove_samplingFrequencyUnit', 'jhove_x_resolution',
       'jhove_y_resolution'])
    all_results.append(tmp)

jhove_chunk_20240611_00000001.csv
jhove_chunk_20240611_00000002.csv
jhove_chunk_20240611_00000003.csv
jhove_chunk_20240611_00000004.csv
jhove_chunk_20240611_00000005.csv
jhove_chunk_20240611_00000006.csv
jhove_chunk_20240611_00000007.csv
jhove_chunk_20240611_00000008.csv
jhove_chunk_20240611_00000009.csv
jhove_chunk_20240611_00000010.csv
jhove_chunk_20240611_00000011.csv
jhove_chunk_20240611_00000012.csv
jhove_chunk_20240611_00000013.csv
jhove_chunk_20240611_00000014.csv
jhove_chunk_20240611_00000015.csv
jhove_chunk_20240611_00000016.csv
jhove_chunk_20240611_00000017.csv
jhove_chunk_20240611_00000018.csv
jhove_chunk_20240611_00000019.csv
jhove_chunk_20240611_00000020.csv
jhove_chunk_20240611_00000021.csv
jhove_chunk_20240611_00000022.csv
jhove_chunk_20240611_00000023.csv
jhove_chunk_20240611_00000024.csv
jhove_chunk_20240611_00000025.csv
jhove_chunk_20240611_00000026.csv
jhove_chunk_20240611_00000027.csv
jhove_chunk_20240611_00000028.csv
jhove_chunk_20240611_00000029.csv
jhove_chunk_20240611_00000030.csv
jhove_chunk_20240611_00000031.csv
jhove_chunk_20240611_00000032.csv
jhove_chunk_20240611_00000033.csv
jhove_chunk_20240611_00000034.csv
jhove_chunk_20240611_00000035.csv
jhove_chunk_20240611_00000036.csv
jhove_chunk_20240611_00000037.csv
jhove_chunk_20240611_00000038.csv
jhove_chunk_20240611_00000039.csv
jhove_chunk_20240611_00000040.csv
jhove_chunk_20240611_00000041.csv
jhove_chunk_20240611_00000042.csv
jhove_chunk_20240611_00000043.csv
jhove_chunk_20240611_00000044.csv
jhove_chunk_20240611_00000045.csv
jhove_chunk_20240611_00000046.csv
jhove_chunk_20240611_00000047.csv
jhove_chunk_20240611_00000048.csv
jhove_chunk_20240611_00000049.csv
jhove_chunk_20240611_00000050.csv
jhove_chunk_20240611_00000051.csv
jhove_chunk_20240611_00000052.csv
jhove_chunk_20240611_00000053.csv
jhove_chunk_20240611_00000054.csv
jhove_chunk_20240611_00000055.csv
jhove_chunk_20240611_00000056.csv
jhove_chunk_20240611_00000057.csv
jhove_chunk_20240611_00000058.csv
jhove_chunk_20240611_00000059.csv
jhove_chunk_20240611_00000060.csv
jhove_chunk_20240611_00000061.csv
jhove_chunk_20240611_00000062.csv
jhove_chunk_20240611_00000063.csv
jhove_chunk_20240611_00000064.csv
jhove_chunk_20240611_00000065.csv
jhove_chunk_20240611_00000066.csv
jhove_chunk_20240611_00000067.csv
jhove_chunk_20240611_00000068.csv
jhove_chunk_20240611_00000069.csv
jhove_chunk_20240611_00000070.csv
jhove_chunk_20240611_00000071.csv
jhove_chunk_20240611_00000072.csv
jhove_chunk_20240611_00000073.csv
jhove_chunk_20240611_00000074.csv
jhove_chunk_20240611_00000075.csv
jhove_chunk_20240611_00000076.csv
jhove_chunk_20240611_00000077.csv
jhove_chunk_20240611_00000078.csv
jhove_chunk_20240611_00000079.csv
jhove_chunk_20240611_00000080.csv
jhove_chunk_20240611_00000081.csv
jhove_chunk_20240611_00000082.csv
jhove_chunk_20240611_00000083.csv
jhove_chunk_20240611_00000084.csv
jhove_chunk_20240611_00000085.csv
jhove_chunk_20240611_00000086.csv
jhove_chunk_20240611_00000087.csv
jhove_chunk_20240611_00000088.csv
jhove_chunk_20240611_00000089.csv
jhove_chunk_20240611_00000090.csv
jhove_chunk_20240611_00000091.csv
jhove_chunk_20240611_00000092.csv
jhove_chunk_20240611_00000093.csv
jhove_chunk_20240611_00000094.csv
jhove_chunk_20240611_00000095.csv
jhove_chunk_20240611_00000096.csv
jhove_chunk_20240611_00000097.csv
jhove_chunk_20240611_00000098.csv
jhove_chunk_20240611_00000099.csv
jhove_chunk_20240611_00000100.csv
jhove_chunk_20240611_00000101.csv
jhove_chunk_20240611_00000102.csv
jhove_chunk_20240611_00000103.csv
jhove_chunk_20240611_00000104.csv
jhove_chunk_20240611_00000105.csv
jhove_chunk_20240611_00000106.csv
jhove_chunk_20240611_00000107.csv
jhove_chunk_20240611_00000108.csv
jhove_chunk_20240611_00000109.csv
jhove_chunk_20240611_00000110.csv
jhove_chunk_20240611_00000111.csv
jhove_chunk_20240611_00000112.csv
jhove_chunk_20240611_00000113.csv
jhove_chunk_20240611_00000114.csv
jhove_chunk_20240611_00000115.csv
jhove_chunk_20240611_00000116.csv
jhove_chunk_20240611_00000117.csv
jhove_chunk_20240611_00000118.csv
jhove_chunk_20240611_00000119.csv
jhove_chunk_20240611_00000120.csv
jhove_chunk_20240611_00000121.csv
jhove_chunk_20240611_00000122.csv
jhove_chunk_20240611_00000123.csv
jhove_chunk_20240611_00000124.csv
jhove_chunk_20240611_00000125.csv
jhove_chunk_20240611_00000126.csv
jhove_chunk_20240611_00000127.csv
jhove_chunk_20240611_00000128.csv
jhove_chunk_20240611_00000129.csv
jhove_chunk_20240611_00000130.csv
jhove_chunk_20240611_00000131.csv
jhove_chunk_20240611_00000132.csv
jhove_chunk_20240611_00000133.csv
jhove_chunk_20240611_00000134.csv
jhove_chunk_20240611_00000135.csv
jhove_chunk_20240611_00000136.csv
jhove_chunk_20240611_00000137.csv
jhove_chunk_20240611_00000138.csv
jhove_chunk_20240611_00000139.csv
jhove_chunk_20240611_00000140.csv
jhove_chunk_20240611_00000141.csv
jhove_chunk_20240611_00000142.csv
jhove_chunk_20240611_00000143.csv
jhove_chunk_20240611_00000144.csv
jhove_chunk_20240611_00000145.csv
jhove_chunk_20240611_00000146.csv
jhove_chunk_20240611_00000147.csv
jhove_chunk_20240611_00000148.csv
jhove_chunk_20240611_00000149.csv
jhove_chunk_20240611_00000150.csv
jhove_chunk_20240611_00000151.csv
jhove_chunk_20240611_00000152.csv
jhove_chunk_20240611_00000153.csv
jhove_chunk_20240611_00000154.csv
jhove_chunk_20240611_00000155.csv
jhove_chunk_20240611_00000156.csv
jhove_chunk_20240611_00000157.csv
jhove_chunk_20240611_00000158.csv
jhove_chunk_20240611_00000159.csv
jhove_chunk_20240611_00000160.csv
jhove_chunk_20240611_00000161.csv
jhove_chunk_20240611_00000162.csv
jhove_chunk_20240611_00000163.csv
jhove_chunk_20240611_00000164.csv
jhove_chunk_20240611_00000165.csv
jhove_chunk_20240611_00000166.csv
jhove_chunk_20240611_00000167.csv
jhove_chunk_20240611_00000168.csv
jhove_chunk_20240611_00000169.csv
jhove_chunk_20240611_00000170.csv
jhove_chunk_20240611_00000171.csv
jhove_chunk_20240611_00000172.csv
jhove_chunk_20240611_00000173.csv
jhove_chunk_20240611_00000174.csv
jhove_chunk_20240611_00000175.csv
jhove_chunk_20240611_00000176.csv
jhove_chunk_20240611_00000177.csv
jhove_chunk_20240611_00000178.csv
jhove_chunk_20240611_00000179.csv
jhove_chunk_20240611_00000180.csv
jhove_chunk_20240611_00000181.csv
jhove_chunk_20240611_00000182.csv
jhove_chunk_20240611_00000183.csv
jhove_chunk_20240611_00000184.csv
jhove_chunk_20240611_00000185.csv
jhove_chunk_20240611_00000186.csv
jhove_chunk_20240611_00000187.csv
jhove_chunk_20240611_00000188.csv
jhove_chunk_20240611_00000189.csv
jhove_chunk_20240611_00000190.csv
jhove_chunk_20240611_00000191.csv
jhove_chunk_20240611_00000192.csv
jhove_chunk_20240611_00000193.csv
jhove_chunk_20240611_00000194.csv
jhove_chunk_20240611_00000195.csv
jhove_chunk_20240611_00000196.csv
jhove_chunk_20240611_00000197.csv
jhove_chunk_20240611_00000198.csv
jhove_chunk_20240611_00000199.csv
jhove_chunk_20240611_00000200.csv
jhove_chunk_20240611_00000201.csv
jhove_chunk_20240611_00000202.csv
jhove_chunk_20240611_00000203.csv
jhove_chunk_20240611_00000204.csv
jhove_chunk_20240611_00000205.csv
jhove_chunk_20240611_00000206.csv
jhove_chunk_20240611_00000207.csv
jhove_chunk_20240611_00000209.csv
jhove_chunk_20240611_00000211.csv
jhove_chunk_20240611_00000212.csv
jhove_chunk_20240611_00000213.csv
jhove_chunk_20240611_00000214.csv
jhove_chunk_20240611_00000216.csv
jhove_chunk_20240611_00000217.csv
jhove_chunk_20240611_00000218.csv
jhove_chunk_20240611_00000219.csv
jhove_chunk_20240611_00000220.csv
jhove_chunk_20240611_00000221.csv
jhove_chunk_20240611_00000222.csv
jhove_chunk_20240611_00000223.csv
jhove_chunk_20240611_00000224.csv
jhove_chunk_20240611_00000225.csv
jhove_chunk_20240611_00000226.csv
jhove_chunk_20240611_00000227.csv
jhove_chunk_20240611_00000228.csv
jhove_chunk_20240611_00000229.csv
jhove_chunk_20240611_00000230.csv
jhove_chunk_20240611_00000231.csv
jhove_chunk_20240611_00000232.csv
jhove_chunk_20240611_00000233.csv
jhove_chunk_20240611_00000234.csv
jhove_chunk_20240611_00000235.csv
jhove_chunk_20240611_00000236.csv
jhove_chunk_20240611_00000237.csv
jhove_chunk_20240611_00000238.csv
jhove_chunk_20240611_00000239.csv
jhove_chunk_20240611_00000240.csv
jhove_chunk_20240611_00000241.csv
jhove_chunk_20240611_00000242.csv
jhove_chunk_20240611_00000243.csv
jhove_chunk_20240611_00000244.csv
jhove_chunk_20240611_00000245.csv
jhove_chunk_20240611_00000246.csv
jhove_chunk_20240611_00000247.csv
jhove_chunk_20240611_00000248.csv
jhove_chunk_20240611_00000249.csv
jhove_chunk_20240611_00000250.csv
jhove_chunk_20240611_00000251.csv
jhove_chunk_20240611_00000252.csv
jhove_chunk_20240611_00000253.csv
jhove_chunk_20240611_00000254.csv
jhove_chunk_20240611_00000255.csv
jhove_chunk_20240611_00000256.csv
jhove_chunk_20240611_00000257.csv
jhove_chunk_20240611_00000258.csv
jhove_chunk_20240611_00000259.csv
jhove_chunk_20240611_00000260.csv
jhove_chunk_20240611_00000261.csv
jhove_chunk_20240611_00000262.csv
jhove_chunk_20240611_00000263.csv
jhove_chunk_20240611_00000264.csv
jhove_chunk_20240611_00000265.csv
jhove_chunk_20240611_00000266.csv
jhove_chunk_20240611_00000267.csv
jhove_chunk_20240611_00000268.csv
jhove_chunk_20240611_00000269.csv
jhove_chunk_20240611_00000270.csv
jhove_chunk_20240611_00000271.csv
jhove_chunk_20240611_00000272.csv
jhove_chunk_20240611_00000273.csv
jhove_chunk_20240611_00000274.csv
jhove_chunk_20240611_00000275.csv
jhove_chunk_20240611_00000276.csv
jhove_chunk_20240611_00000277.csv
jhove_chunk_20240611_00000278.csv
jhove_chunk_20240611_00000279.csv
jhove_chunk_20240611_00000280.csv
jhove_chunk_20240611_00000281.csv
jhove_chunk_20240611_00000282.csv
jhove_chunk_20240611_00000283.csv
jhove_chunk_20240611_00000284.csv
jhove_chunk_20240611_00000285.csv
jhove_chunk_20240611_00000286.csv
jhove_chunk_20240611_00000287.csv
jhove_chunk_20240611_00000288.csv
jhove_chunk_20240611_00000289.csv
jhove_chunk_20240611_00000290.csv
jhove_chunk_20240611_00000291.csv
jhove_chunk_20240611_00000292.csv
jhove_chunk_20240611_00000293.csv
jhove_chunk_20240611_00000294.csv
jhove_chunk_20240611_00000295.csv
jhove_chunk_20240611_00000296.csv
jhove_chunk_20240611_00000297.csv
jhove_chunk_20240611_00000298.csv
jhove_chunk_20240611_00000299.csv
jhove_chunk_20240611_00000300.csv
jhove_chunk_20240611_00000301.csv
jhove_chunk_20240611_00000302.csv
jhove_chunk_20240611_00000303.csv
jhove_chunk_20240611_00000304.csv
jhove_chunk_20240611_00000305.csv
jhove_chunk_20240611_00000306.csv
jhove_chunk_20240611_00000307.csv
jhove_chunk_20240611_00000308.csv
jhove_chunk_20240611_00000309.csv
jhove_chunk_20240611_00000310.csv
jhove_chunk_20240611_00000311.csv
jhove_chunk_20240611_00000312.csv
jhove_chunk_20240611_00000313.csv
jhove_chunk_20240611_00000314.csv
jhove_chunk_20240611_00000315.csv
jhove_chunk_20240611_00000316.csv
jhove_chunk_20240611_00000317.csv
jhove_chunk_20240611_00000318.csv
jhove_chunk_20240611_00000319.csv
jhove_chunk_20240611_00000320.csv
jhove_chunk_20240611_00000321.csv
jhove_chunk_20240611_00000322.csv
jhove_chunk_20240611_00000323.csv
jhove_chunk_20240611_00000324.csv
jhove_chunk_20240611_00000325.csv
jhove_chunk_20240611_00000326.csv
jhove_chunk_20240611_00000327.csv
jhove_chunk_20240611_00000328.csv
jhove_chunk_20240611_00000329.csv
jhove_chunk_20240611_00000330.csv
jhove_chunk_20240611_00000331.csv
jhove_chunk_20240611_00000332.csv
jhove_chunk_20240611_00000333.csv
jhove_chunk_20240611_00000334.csv
jhove_chunk_20240611_00000335.csv
jhove_chunk_20240611_00000336.csv
jhove_chunk_20240611_00000337.csv
jhove_chunk_20240611_00000338.csv
jhove_chunk_20240611_00000339.csv
jhove_chunk_20240611_00000340.csv
jhove_chunk_20240611_00000341.csv
jhove_chunk_20240611_00000342.csv
jhove_chunk_20240611_00000343.csv
jhove_chunk_20240611_00000344.csv
jhove_chunk_20240611_00000345.csv
jhove_chunk_20240611_00000346.csv
jhove_chunk_20240611_00000347.csv
jhove_chunk_20240611_00000348.csv
jhove_chunk_20240611_00000349.csv
jhove_chunk_20240611_00000350.csv
jhove_chunk_20240611_00000351.csv
jhove_chunk_20240611_00000352.csv
jhove_chunk_20240611_00000353.csv
jhove_chunk_20240611_00000354.csv
jhove_chunk_20240611_00000355.csv
jhove_chunk_20240611_00000356.csv
jhove_chunk_20240611_00000357.csv
jhove_chunk_20240611_00000358.csv
jhove_chunk_20240611_00000359.csv
jhove_chunk_20240611_00000360.csv
jhove_chunk_20240611_00000361.csv
jhove_chunk_20240611_00000362.csv
jhove_chunk_20240611_00000363.csv
jhove_chunk_20240611_00000364.csv
jhove_chunk_20240611_00000365.csv
jhove_chunk_20240611_00000366.csv
jhove_chunk_20240611_00000367.csv
jhove_chunk_20240611_00000368.csv
jhove_chunk_20240611_00000369.csv
jhove_chunk_20240611_00000370.csv
jhove_chunk_20240611_00000371.csv
jhove_chunk_20240611_00000372.csv
jhove_chunk_20240611_00000373.csv
jhove_chunk_20240611_00000374.csv
jhove_chunk_20240611_00000375.csv
jhove_chunk_20240611_00000376.csv
jhove_chunk_20240611_00000377.csv
jhove_chunk_20240611_00000378.csv
jhove_chunk_20240611_00000379.csv
jhove_chunk_20240611_00000380.csv
jhove_chunk_20240611_00000381.csv
jhove_chunk_20240611_00000382.csv
jhove_chunk_20240611_00000383.csv
jhove_chunk_20240611_00000384.csv
jhove_chunk_20240611_00000385.csv
jhove_chunk_20240611_00000386.csv
jhove_chunk_20240611_00000387.csv
jhove_chunk_20240611_00000388.csv
jhove_chunk_20240611_00000389.csv
jhove_chunk_20240611_00000390.csv
jhove_chunk_20240611_00000391.csv
jhove_chunk_20240611_00000392.csv
jhove_chunk_20240611_00000393.csv
jhove_chunk_20240611_00000394.csv
jhove_chunk_20240611_00000395.csv
jhove_chunk_20240611_00000396.csv
jhove_chunk_20240611_00000397.csv
jhove_chunk_20240611_00000398.csv
jhove_chunk_20240611_00000399.csv
jhove_chunk_20240611_00000400.csv
jhove_chunk_20240611_00000401.csv
jhove_chunk_20240611_00000402.csv
jhove_chunk_20240611_00000403.csv
jhove_chunk_20240611_00000404.csv
jhove_chunk_20240611_00000405.csv
jhove_chunk_20240611_00000406.csv
jhove_chunk_20240611_00000407.csv
jhove_chunk_20240611_00000408.csv
jhove_chunk_20240611_00000409.csv
jhove_chunk_20240611_00000410.csv
jhove_chunk_20240611_00000411.csv
jhove_chunk_20240611_00000412.csv
jhove_chunk_20240611_00000413.csv
jhove_chunk_20240611_00000414.csv
jhove_chunk_20240611_00000415.csv
jhove_chunk_20240611_00000416.csv
jhove_chunk_20240611_00000417.csv
jhove_chunk_20240611_00000418.csv
jhove_chunk_20240611_00000419.csv
jhove_chunk_20240611_00000420.csv
jhove_chunk_20240611_00000421.csv
jhove_chunk_20240611_00000422.csv
jhove_chunk_20240611_00000423.csv
jhove_chunk_20240611_00000424.csv
jhove_chunk_20240611_00000425.csv
jhove_chunk_20240611_00000426.csv
jhove_chunk_20240611_00000427.csv
jhove_chunk_20240611_00000428.csv
jhove_chunk_20240611_00000429.csv
jhove_chunk_20240611_00000430.csv
jhove_chunk_20240611_00000431.csv
jhove_chunk_20240611_00000432.csv
jhove_chunk_20240611_00000433.csv
jhove_chunk_20240611_00000434.csv
jhove_chunk_20240611_00000435.csv
jhove_chunk_20240611_00000436.csv
jhove_chunk_20240611_00000437.csv
jhove_chunk_20240611_00000438.csv
jhove_chunk_20240611_00000439.csv
jhove_chunk_20240611_00000440.csv
jhove_chunk_20240611_00000441.csv
jhove_chunk_20240611_00000442.csv
jhove_chunk_20240611_00000443.csv
jhove_chunk_20240611_00000444.csv
jhove_chunk_20240611_00000445.csv
jhove_chunk_20240611_00000446.csv
jhove_chunk_20240611_00000447.csv
jhove_chunk_20240611_00000448.csv
jhove_chunk_20240611_00000449.csv
jhove_chunk_20240611_00000450.csv
jhove_chunk_20240611_00000451.csv
jhove_chunk_20240611_00000452.csv
jhove_chunk_20240611_00000453.csv
jhove_chunk_20240611_00000454.csv
jhove_chunk_20240611_00000455.csv
jhove_chunk_20240611_00000456.csv
jhove_chunk_20240611_00000457.csv
jhove_chunk_20240611_00000458.csv
jhove_chunk_20240611_00000459.csv
jhove_chunk_20240611_00000460.csv
jhove_chunk_20240611_00000461.csv
jhove_chunk_20240611_00000462.csv
jhove_chunk_20240611_00000463.csv
jhove_chunk_20240611_00000464.csv
jhove_chunk_20240611_00000465.csv
jhove_chunk_20240611_00000466.csv
jhove_chunk_20240611_00000467.csv
jhove_chunk_20240611_00000468.csv
jhove_chunk_20240611_00000469.csv
jhove_chunk_20240611_00000470.csv
jhove_chunk_20240611_00000472.csv
jhove_chunk_20240611_00000473.csv
jhove_chunk_20240611_00000474.csv
jhove_chunk_20240611_00000475.csv
jhove_chunk_20240611_00000476.csv
jhove_chunk_20240611_00000477.csv
jhove_chunk_20240611_00000478.csv
jhove_chunk_20240611_00000479.csv
jhove_chunk_20240611_00000480.csv
jhove_chunk_20240611_00000481.csv
jhove_chunk_20240611_00000482.csv
jhove_chunk_20240611_00000483.csv
jhove_chunk_20240611_00000484.csv
jhove_chunk_20240611_00000485.csv
jhove_chunk_20240611_00000486.csv
jhove_chunk_20240611_00000487.csv
jhove_chunk_20240611_00000488.csv
jhove_chunk_20240611_00000489.csv
jhove_chunk_20240611_00000490.csv
jhove_chunk_20240611_00000491.csv
jhove_chunk_20240611_00000492.csv
jhove_chunk_20240611_00000493.csv
jhove_chunk_20240611_00000494.csv
jhove_chunk_20240611_00000495.csv
jhove_chunk_20240611_00000496.csv
jhove_chunk_20240611_00000497.csv
jhove_chunk_20240611_00000498.csv
jhove_chunk_20240611_00000499.csv
jhove_chunk_20240611_00000500.csv
jhove_chunk_20240611_00001501.csv
jhove_chunk_20240611_00001502.csv
jhove_chunk_20240611_00001503.csv
jhove_chunk_20240611_00001504.csv
jhove_chunk_20240611_00001505.csv
jhove_chunk_20240611_00001506.csv
jhove_chunk_20240611_00001507.csv
jhove_chunk_20240611_00001508.csv
jhove_chunk_20240611_00001509.csv
jhove_chunk_20240611_00001510.csv
jhove_chunk_20240611_00001511.csv
jhove_chunk_20240611_00001512.csv
jhove_chunk_20240611_00001513.csv
jhove_chunk_20240611_00001514.csv
jhove_chunk_20240611_00001515.csv
jhove_chunk_20240611_00001516.csv
jhove_chunk_20240611_00001517.csv
jhove_chunk_20240611_00001518.csv
jhove_chunk_20240611_00001519.csv
jhove_chunk_20240611_00001520.csv
jhove_chunk_20240611_00001521.csv
jhove_chunk_20240611_00001522.csv
jhove_chunk_20240611_00001523.csv
jhove_chunk_20240611_00001524.csv
jhove_chunk_20240611_00001525.csv
jhove_chunk_20240611_00001526.csv
jhove_chunk_20240611_00001527.csv
jhove_chunk_20240611_00001528.csv
jhove_chunk_20240611_00001529.csv
jhove_chunk_20240611_00001530.csv
jhove_chunk_20240611_00001531.csv
jhove_chunk_20240611_00001532.csv
jhove_chunk_20240611_00001533.csv
jhove_chunk_20240611_00001534.csv
jhove_chunk_20240611_00001535.csv
jhove_chunk_20240611_00001536.csv
jhove_chunk_20240611_00001537.csv
jhove_chunk_20240611_00001538.csv
jhove_chunk_20240611_00001539.csv
jhove_chunk_20240611_00001540.csv
jhove_chunk_20240611_00001541.csv
jhove_chunk_20240611_00001542.csv
jhove_chunk_20240611_00001543.csv
jhove_chunk_20240611_00001544.csv
jhove_chunk_20240611_00001545.csv
jhove_chunk_20240611_00001546.csv
jhove_chunk_20240611_00001547.csv
jhove_chunk_20240611_00001548.csv
jhove_chunk_20240611_00001549.csv
jhove_chunk_20240611_00001550.csv
jhove_chunk_20240611_00001551.csv
jhove_chunk_20240611_00001552.csv
jhove_chunk_20240611_00001553.csv
jhove_chunk_20240611_00001554.csv
jhove_chunk_20240611_00001555.csv
jhove_chunk_20240611_00001556.csv
jhove_chunk_20240611_00001557.csv
jhove_chunk_20240611_00001558.csv
jhove_chunk_20240611_00001559.csv
jhove_chunk_20240611_00001560.csv
jhove_chunk_20240611_00001561.csv
jhove_chunk_20240611_00001562.csv
jhove_chunk_20240611_00001563.csv
jhove_chunk_20240611_00001564.csv
jhove_chunk_20240611_00001565.csv
jhove_chunk_20240611_00001566.csv
jhove_chunk_20240611_00001567.csv
jhove_chunk_20240611_00001568.csv
jhove_chunk_20240611_00001569.csv
jhove_chunk_20240611_00001570.csv
jhove_chunk_20240611_00001571.csv
jhove_chunk_20240611_00001572.csv
jhove_chunk_20240611_00001573.csv
jhove_chunk_20240611_00001574.csv
jhove_chunk_20240611_00001575.csv
jhove_chunk_20240611_00001576.csv
jhove_chunk_20240611_00001577.csv
jhove_chunk_20240611_00001578.csv
jhove_chunk_20240611_00001579.csv
jhove_chunk_20240611_00001580.csv
jhove_chunk_20240611_00001581.csv
jhove_chunk_20240611_00001582.csv
jhove_chunk_20240611_00001583.csv
jhove_chunk_20240611_00001584.csv
jhove_chunk_20240611_00001585.csv
jhove_chunk_20240611_00001586.csv
jhove_chunk_20240611_00001587.csv
jhove_chunk_20240611_00001588.csv
jhove_chunk_20240611_00001589.csv
jhove_chunk_20240611_00001590.csv
jhove_chunk_20240611_00001591.csv
jhove_chunk_20240611_00001592.csv

In [5]:
len(all_results)

1327

In [7]:
all_results[0].columns

Index(['jhove_uri', 'jhove_lastModified', 'jhove_format', 'jhove_version',
       'jhove_mimeType', 'jhove_size', 'jhove_imageWidth', 'jhove_imageHeight',
       'jhove_samplingFrequencyUnit', 'jhove_x_resolution',
       'jhove_y_resolution'],
      dtype='object')

In [3]:
df = pd.DataFrame(columns=['jhove_uri', 'jhove_lastModified', 'jhove_format', 'jhove_version',
       'jhove_mimeType', 'jhove_size', 'jhove_imageWidth', 'jhove_imageHeight',
       'jhove_samplingFrequencyUnit', 'jhove_x_resolution',
       'jhove_y_resolution'])
df

Empty DataFrame
Columns: [jhove_uri, jhove_lastModified, jhove_format, jhove_version, jhove_mimeType, jhove_size, jhove_imageWidth, jhove_imageHeight, jhove_samplingFrequencyUnit, jhove_x_resolution, jhove_y_resolution]
Index: []

In [4]:
df = pd.concat(all_results)

In [14]:
df

,jhove_uri,jhove_lastModified,jhove_format,jhove_version,jhove_mimeType,jhove_size,jhove_imageWidth,jhove_imageHeight,jhove_samplingFrequencyUnit,jhove_x_resolution,jhove_y_resolution
0,BNR_SAUV/AMR/AMR_AFF/RBX_AMR_AFF_001_D_0001_1.tif,2012-08-30T13:31:10+02:00,TIFF,5.0,image/tiff,143190155.0,7840.0,6088.0,in.,300.0,300.0
1,BNR_SAUV/AMR/AMR_AFF/RBX_AMR_AFF_001_D_0002_1.tif,2012-08-30T13:31:12+02:00,TIFF,5.0,image/tiff,73202507.0,4008.0,6088.0,in.,300.0,300.0
2,BNR_SAUV/AMR/AMR_AFF/RBX_AMR_AFF_001_D_0003_1.tif,2012-08-30T13:33:10+02:00,TIFF,5.0,image/tiff,175634315.0,6776.0,8640.0,in.,300.0,300.0
3,BNR_SAUV/AMR/AMR_AFF/RBX_AMR_AFF_001_D_0004_1.tif,2012-08-30T13:33:12+02:00,TIFF,5.0,image/tiff,133094411.0,6224.0,7128.0,in.,300.0,300.0
4,BNR_SAUV/AMR/AMR_AFF/RBX_AMR_AFF_001_D_0005_1.tif,2012-08-30T13:34:34+02:00,TIFF,5.0,image/tiff,142771211.0,6064.0,7848.0,in.,300.0,300.0
...,...,...,...,...,...,...,...,...,...,...,...
1023,600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1024,DPI/PLS/PLS_198.tif,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1025,Procedures/1_parties_serveur_stockage_141220.pdf,2015-06-04T14:17:12+02:00,PDF,1.4,application/pdf,9396.0,NaN,NaN,NaN,NaN,NaN
1026,Procedures/2_Organisation_BnR_Sauv_BnR_tampon_...,2015-06-04T14:17:33+02:00,PDF,1.4,application/pdf,12243.0,NaN,NaN,NaN,NaN,NaN
1027,Procedures/3_Organisation_BnR_verif_transfert_...,2015-06-04T14:17:50+02:00,PDF,1.4,application/pdf,13522.0,NaN,NaN,NaN,NaN,NaN

In [5]:
df.to_csv("data/jhove_synthese_20240615.csv.gz", index=False)

In [17]:
df['jhove_x_resolution'].median()

300.0

In [15]:
bplot = df.boxplot(column=df['jhove_x_resolution'])

In [17]:
import seaborn as sns

In [25]:
jxres = df['jhove_x_resolution'][~df['jhove_x_resolution'].isna()]
jxres = jxres.astype(int)
sns.boxplot(x=jxres)

In [26]:
jxres.value_counts()

jhove_x_resolution
300     104558
200      36424
400      31315
201       1479
96        1025
2400      1013
198        912
299        757
350        428
72         414
612        300
240         95
157         95
597         62
100          8
150          5
600          3
622          2
607          2
628          1
605          1
Name: count, dtype: int64

In [34]:
import numpy as np
data = np.random.randn(5000, 2)
df0 = pd.DataFrame(data, columns=['x', 'y'])
df0

             x         y
0     0.398762 -1.081906
1    -0.363028  0.856103
2    -0.405102  0.851232
3     1.020701  0.066126
4     1.436776 -1.839780
...        ...       ...
4995 -0.597574 -0.347843
4996 -0.992504 -0.806604
4997 -0.471922 -1.410214
4998  0.815707  0.361915
4999 -0.596924 -0.330277

[5000 rows x 2 columns]

In [33]:
sns.boxplot(data=df0, x='x')